### ISSUE TITLE
Problem testing the UpWork Example App

### ISSUE THREAD

**Issue by Shajeel-Afzal** [upwork/java-upwork#6]
Hi, 

I imported UpWork Example App in Eclipse and added my secret and secret, now i am getting the after running the app. 

```
{"version":"0.6","errors":[{"reason":"invalid_query","message":"The provided API Key has wrong format."}],"status":"error"}
{"error":{"code":"400","message":"The provided API Key has wrong format."}}
```
Also if i try to run the project with token and secret provided null then i get the following response: 

```
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 400 (Bad Request)
null
1. Copy paste the following url in your browser : 
	at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:218)
	at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74)
	at com.Upwork.api.OAuthClient._getAuthorizationUrl(OAuthClient.java:254)
	at com.Upwork.api.OAuthClient.getAuthorizationUrl(OAuthClient.java:113)
	at TestApi.main(TestApi.java:32)
Caused by: oauth.signpost.exception.OAuthCommunicationException: Service provider responded in error: 400 (Bad Request)
	at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:245)
	at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
	... 4 more
null
2. Grant access 
3. Copy paste the oauth_verifier parameter here :
```

**Comment by mnovozhylov** [comment]
1. please read how https://developers.upwork.com/?lang=java#authentication_oauth-10 works
2. type your key/secret im upwork.properties
3. type you access_token/access_token_secret (if needed, normally you should keep them in a safe place according to the security policy of your app) only when you receive them at the end of authorization
